<a href="https://colab.research.google.com/github/mazarimono/python-data-seminar/blob/main/Chapter5_1_%E3%83%87%E3%83%BC%E3%82%BF%E3%81%AE%E8%AA%AD%E3%81%BF%E8%BE%BC%E3%81%BF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## パッケージのインポート

In [1]:
from pathlib import Path
from zipfile import ZipFile
import geopandas as gpd
import pandas as pd
import plotly.express as px

## ZIPファイルを操作する

In [2]:
# パスをコピペして貼り付け、プリント
a_path = '/content/drive/MyDrive/od-book/国勢調査/A002005212020DDSWC27.zip'
t_path = '/content/drive/MyDrive/od-book/国勢調査/tblT001082C27.zip'
print(a_path)
print(t_path)

/content/drive/MyDrive/od-book/国勢調査/A002005212020DDSWC27.zip
/content/drive/MyDrive/od-book/国勢調査/tblT001082C27.zip

In [3]:
# Pathオブジェクトにして、変数に渡す
toukei_zip_path = Path(t_path)
kyokai_zip_path = Path(a_path)

# 様々な操作が容易になる
print(toukei_zip_path.name)
print(toukei_zip_path.stem)
print(toukei_zip_path.parent)

tblT001082C27.zip
tblT001082C27
/content/drive/MyDrive/od-book/国勢調査

### コード5-1

In [5]:
# ZIPファイルに格納されているファイル情報を表示
with ZipFile(toukei_zip_path, 'r') as toukei_zip:
    toukei_zip_info = toukei_zip.infolist()
print(toukei_zip_info)

[<ZipInfo filename='tblT001082C27.txt' compress_type=deflate filemode='-rw-r--r--' file_size=2384693 compress_size=851590>]

In [6]:
with ZipFile(kyokai_zip_path, 'r') as kyokai_zip:
    kyokai_zip_name = kyokai_zip.infolist()
print(kyokai_zip_name)

[<ZipInfo filename='r2ka27.prj' compress_type=deflate filemode='-rw-r--r--' file_size=147 compress_size=128>, <ZipInfo filename='r2ka27.dbf' compress_type=deflate filemode='-rw-r--r--' file_size=2603375 compress_size=494928>, <ZipInfo filename='r2ka27.shx' compress_type=deflate filemode='-rw-r--r--' file_size=71644 compress_size=41756>, <ZipInfo filename='r2ka27.shp' compress_type=deflate filemode='-rw-r--r--' file_size=11855092 compress_size=6643789>]

## データの読み込み

In [7]:
# CSVファイルの読み込み
toukei_df = pd.read_csv(toukei_zip_path)

UnicodeDecodeError: ignored

In [8]:
toukei_df = pd.read_csv(toukei_zip_path, encoding='cp932')
toukei_df.head()

,KEY_CODE,HYOSYO,CITYNAME,NAME,HTKSYORI,HTKSAKI,GASSAN,T001082001,T001082002,T001082003,...,T001082051,T001082052,T001082053,T001082054,T001082055,T001082056,T001082057,T001082058,T001082059,T001082060
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,総数、年齢「不詳」含む,総数０～４歳,総数５～９歳,...,女４５～４９歳,女５０～５４歳,女５５～５９歳,女６０～６４歳,女６５～６９歳,女７０～７４歳,女１５歳未満,女１５～６４歳,女６５歳以上,女７５歳以上
1,2.710200e+04,1.0,大阪市都島区,NaN,0.0,NaN,NaN,107904,3785,4069,...,4238,3643,3243,3012,3119,3413,5743,33518,14421,7889
2,2.710200e+08,3.0,大阪市都島区,片町,0.0,NaN,NaN,2408,67,30,...,84,66,49,38,33,41,49,833,125,51
3,2.710200e+10,4.0,大阪市都島区,片町一丁目,0.0,NaN,NaN,1562,47,27,...,59,49,34,27,22,24,38,554,74,28
4,2.710200e+10,4.0,大阪市都島区,片町二丁目,0.0,NaN,NaN,846,20,3,...,25,17,15,11,11,17,11,279,51,23

In [9]:
gis_df = gpd.read_file(kyokai_zip_path)
gis_df.head()

,KEY_CODE,PREF,CITY,S_AREA,PREF_NAME,CITY_NAME,S_NAME,KIGO_E,HCODE,AREA,...,N_KEN,N_CITY,KIGO_I,KBSUM,JINKO,SETAI,X_CODE,Y_CODE,KCODE1,geometry
0,27,27,362,000000,大阪府,田尻町,NaN,NaN,8101,75145.022,...,NaN,NaN,NaN,0,0,0,135.286628,34.397788,0000-00,"POLYGON ((135.28779 34.39860, 135.28818 34.398..."
1,27102001001,27,102,001001,大阪府,大阪市都島区,片町一丁目,NaN,8101,102717.230,...,NaN,NaN,NaN,14,1562,1155,135.524883,34.692489,0010-01,"POLYGON ((135.52721 34.69363, 135.52724 34.693..."
2,27102001002,27,102,001002,大阪府,大阪市都島区,片町二丁目,NaN,8101,127975.674,...,NaN,NaN,NaN,15,846,680,135.531182,34.695200,0010-02,"POLYGON ((135.53374 34.69707, 135.53385 34.696..."
3,271020020,27,102,002000,大阪府,大阪市都島区,網島町,NaN,8101,191219.135,...,NaN,NaN,NaN,23,1411,845,135.524147,34.694857,0020-00,"POLYGON ((135.52545 34.69737, 135.52585 34.697..."
4,27102003001,27,102,003001,大阪府,大阪市都島区,東野田町一丁目,NaN,8101,105965.278,...,NaN,NaN,NaN,29,2046,1541,135.528304,34.696303,0030-01,"POLYGON ((135.52775 34.69448, 135.52707 34.694..."